/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Tenant;

import business.EcoSystem;
import business.FeedBackForm;
import business.account.TenantAccount;
import java.awt.CardLayout;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Shruti
 */
public class FeedbackFormJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FeedbackFormJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private TenantAccount tenantAccount;
    

    FeedbackFormJPanel(JPanel userProcessContainer, EcoSystem ecosystem, TenantAccount tenantAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.tenantAccount = tenantAccount;
        if(tenantAccount.isFeedBackSubmitted()){
            displayFeedBack();
        }
        groupElectricianFeedBack();
        groupPlumbingFeedback();
        groupTransportFeedback();
        groupSewageFeedback();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        elecVerySatis = new javax.swing.JRadioButton();
        elecSatis = new javax.swing.JRadioButton();
        elecUnsure = new javax.swing.JRadioButton();
        elecNotSatis = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sewVerySatis = new javax.swing.JRadioButton();
        sewSatis = new javax.swing.JRadioButton();
        sewUnsure = new javax.swing.JRadioButton();
        sewNotSatis = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        plumVerySatis = new javax.swing.JRadioButton();
        plumSatis = new javax.swing.JRadioButton();
        plumUnsure = new javax.swing.JRadioButton();
        plumNotSatis = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        transSatis = new javax.swing.JRadioButton();
        transVerySatis = new javax.swing.JRadioButton();
        transNotSatis = new javax.swing.JRadioButton();
        transUnsure = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        otherComments = new javax.swing.JTextField();
        jSlider = new javax.swing.JSlider();
        jLabel18 = new javax.swing.JLabel();
        submitBttn = new javax.swing.JButton();
        backBttn = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Customer Feedback Form");

        jLabel2.setText("Very Satisfied");

        jLabel3.setText("Satisfied");

        jLabel4.setText("Unsure");

        jLabel5.setText("Not Satisfied");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Electrician"));

        jLabel6.setText("Installation of Equipments considering the Safety Measures");

        elecVerySatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elecVerySatisActionPerformed(evt);
            }
        });

        elecSatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elecSatisActionPerformed(evt);
            }
        });

        elecUnsure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elecUnsureActionPerformed(evt);
            }
        });

        elecNotSatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elecNotSatisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(153, 153, 153)
                .addComponent(elecVerySatis)
                .addGap(86, 86, 86)
                .addComponent(elecSatis)
                .addGap(77, 77, 77)
                .addComponent(elecUnsure)
                .addGap(87, 87, 87)
                .addComponent(elecNotSatis)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(elecNotSatis)
                            .addComponent(elecUnsure)
                            .addComponent(elecSatis)
                            .addComponent(elecVerySatis))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sewage"));

        jLabel8.setText("Functioning of Sewage System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sewVerySatis)
                .addGap(97, 97, 97)
                .addComponent(sewSatis)
                .addGap(79, 79, 79)
                .addComponent(sewUnsure)
                .addGap(73, 73, 73)
                .addComponent(sewNotSatis)
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(sewVerySatis)
                    .addComponent(sewSatis)
                    .addComponent(sewUnsure)
                    .addComponent(sewNotSatis))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Plumbing"));

        jLabel13.setText("Installation of lavitory requirements");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(plumVerySatis)
                .addGap(97, 97, 97)
                .addComponent(plumSatis)
                .addGap(77, 77, 77)
                .addComponent(plumUnsure)
                .addGap(79, 79, 79)
                .addComponent(plumNotSatis)
                .addGap(87, 87, 87))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plumSatis)
                    .addComponent(plumUnsure)
                    .addComponent(plumNotSatis)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addComponent(plumVerySatis))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Transport"));

        jLabel16.setText("How was your vehicle rental experience");

        transSatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transSatisActionPerformed(evt);
            }
        });

        transNotSatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transNotSatisActionPerformed(evt);
            }
        });

        transUnsure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transUnsureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transVerySatis)
                .addGap(95, 95, 95)
                .addComponent(transSatis)
                .addGap(80, 80, 80)
                .addComponent(transUnsure)
                .addGap(83, 83, 83)
                .addComponent(transNotSatis)
                .addGap(83, 83, 83))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transNotSatis)
                    .addComponent(transUnsure)
                    .addComponent(transSatis)
                    .addComponent(transVerySatis)
                    .addComponent(jLabel16))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));

        jLabel17.setText("Any Other Comments");

        jSlider.setMajorTickSpacing(1);
        jSlider.setMaximum(5);
        jSlider.setPaintLabels(true);
        jSlider.setPaintTicks(true);

        jLabel18.setText("Overall Rating");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(otherComments, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(44, 44, 44)
                .addComponent(jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(otherComments, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        submitBttn.setBackground(new java.awt.Color(153, 51, 0));
        submitBttn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        submitBttn.setForeground(new java.awt.Color(255, 255, 255));
        submitBttn.setText("Submit");
        submitBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBttnActionPerformed(evt);
            }
        });

        backBttn.setBackground(new java.awt.Color(153, 51, 0));
        backBttn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        backBttn.setForeground(new java.awt.Color(255, 255, 255));
        backBttn.setText("<< Back");
        backBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(backBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(submitBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(320, 320, 320))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel3)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel4)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel5)
                                .addGap(94, 94, 94))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBttnActionPerformed
           FeedBackForm feedBack = ecosystem.addFeedback();
           //Electrician feedback
           feedBack.setElecVerySatis(elecVerySatis.isSelected());
           feedBack.setElecSatis(elecSatis.isSelected());
           feedBack.setElecUnsure(elecUnsure.isSelected());
           feedBack.setElecNotSatis(elecNotSatis.isSelected());
           
           //Sewage feedback
           feedBack.setSewVerySatis(sewVerySatis.isSelected());
           feedBack.setSewSatis(sewSatis.isSelected());
           feedBack.setSewUnsure(sewUnsure.isSelected());
           feedBack.setSewNotSatis(sewNotSatis.isSelected());
           
           //Plumbing feedback
           feedBack.setPlumVerySatis(plumVerySatis.isSelected());
           feedBack.setPlumSatis(plumSatis.isSelected());
           feedBack.setPlumUnsure(plumUnsure.isSelected());
           feedBack.setPlumNotSatis(plumNotSatis.isSelected());
           
           //Transport feedback
           feedBack.setTransVerySatis(transVerySatis.isSelected());
           feedBack.setTransSatis(transSatis.isSelected());
           feedBack.setTransUnsure(transUnsure.isSelected());
           feedBack.setTransNotSatis(transNotSatis.isSelected());
           
           feedBack.setComments(otherComments.getText());
           feedBack.setRating(jSlider.getValue());
           
           
           tenantAccount.setFeedBackSubmitted(true);
           tenantAccount.setProvidedFeedback(feedBack);
           
           JOptionPane.showMessageDialog(null, "Thank you for Submitting your feedback");
           disableAllFeilds();
           
           
    }//GEN-LAST:event_submitBttnActionPerformed

    private void backBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBttnActionPerformed

    private void transSatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transSatisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transSatisActionPerformed

    private void transUnsureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transUnsureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transUnsureActionPerformed

    private void transNotSatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transNotSatisActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_transNotSatisActionPerformed

    private void elecVerySatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elecVerySatisActionPerformed
        // TODO add your handling code here:
        elecVerySatis.setSelected(true);
    }//GEN-LAST:event_elecVerySatisActionPerformed

    private void elecSatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elecSatisActionPerformed
        // TODO add your handling code here:
         elecSatis.setSelected(true);
    }//GEN-LAST:event_elecSatisActionPerformed

    private void elecUnsureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elecUnsureActionPerformed
        // TODO add your handling code here:
         elecUnsure.setSelected(true);
    }//GEN-LAST:event_elecUnsureActionPerformed

    private void elecNotSatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elecNotSatisActionPerformed
        // TODO add your handling code here:
         elecNotSatis.setSelected(true);
    }//GEN-LAST:event_elecNotSatisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBttn;
    private javax.swing.JRadioButton elecNotSatis;
    private javax.swing.JRadioButton elecSatis;
    private javax.swing.JRadioButton elecUnsure;
    private javax.swing.JRadioButton elecVerySatis;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSlider jSlider;
    private javax.swing.JTextField otherComments;
    private javax.swing.JRadioButton plumNotSatis;
    private javax.swing.JRadioButton plumSatis;
    private javax.swing.JRadioButton plumUnsure;
    private javax.swing.JRadioButton plumVerySatis;
    private javax.swing.JRadioButton sewNotSatis;
    private javax.swing.JRadioButton sewSatis;
    private javax.swing.JRadioButton sewUnsure;
    private javax.swing.JRadioButton sewVerySatis;
    private javax.swing.JButton submitBttn;
    private javax.swing.JRadioButton transNotSatis;
    private javax.swing.JRadioButton transSatis;
    private javax.swing.JRadioButton transUnsure;
    private javax.swing.JRadioButton transVerySatis;
    // End of variables declaration//GEN-END:variables

    private void groupElectricianFeedBack() {
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(elecVerySatis);
        bg1.add(elecSatis);
        bg1.add(elecNotSatis);
        bg1.add(elecUnsure);
    }

    private void groupPlumbingFeedback() {
        ButtonGroup bg2 = new ButtonGroup();
        bg2.add(plumVerySatis);
        bg2.add(plumSatis);
        bg2.add(plumNotSatis);
        bg2.add(plumUnsure);
    }

    private void groupTransportFeedback() {
        ButtonGroup bg3 = new ButtonGroup();
        bg3.add(transVerySatis);
        bg3.add(transSatis);
        bg3.add(transNotSatis);
        bg3.add(transUnsure);
    }

    private void groupSewageFeedback() {
        ButtonGroup bg4 = new ButtonGroup();
        bg4.add(sewVerySatis);
        bg4.add(sewSatis);
        bg4.add(sewNotSatis);
        bg4.add(sewUnsure);
    }

    private void disableAllFeilds() {
        elecVerySatis.setEnabled(false);
        elecSatis.setEnabled(false);
        elecUnsure.setEnabled(false);
        elecNotSatis.setEnabled(false);
        
        
        transVerySatis.setEnabled(false);
        transSatis.setEnabled(false);
        transUnsure.setEnabled(false);
        transNotSatis.setEnabled(false);
        
        
        plumVerySatis.setEnabled(false);
        plumSatis.setEnabled(false);
        plumUnsure.setEnabled(false);
        plumNotSatis.setEnabled(false);
        
        
        sewVerySatis.setEnabled(false);
        sewSatis.setEnabled(false);
        sewUnsure.setEnabled(false);
        sewNotSatis.setEnabled(false);
        
        otherComments.setEnabled(false);
        jSlider.setEnabled(false);
        
        submitBttn.setEnabled(true);
    }

    private void displayFeedBack() {
        FeedBackForm feedBack = tenantAccount.getProvidedFeedback();
        
        elecVerySatis.setSelected(feedBack.isElecVerySatis());
        elecSatis.setSelected(feedBack.isElecSatis());
        elecUnsure.setSelected(feedBack.isElecUnsure());
        elecNotSatis.setSelected(feedBack.isElecNotSatis());
        
        transVerySatis.setSelected(feedBack.isTransVerySatis());
        transSatis.setSelected(feedBack.isTransSatis());
        transUnsure.setSelected(feedBack.isTransUnsure());
        transNotSatis.setSelected(feedBack.isTransNotSatis());
        
        plumVerySatis.setSelected(feedBack.isPlumVerySatis());
        plumSatis.setSelected(feedBack.isPlumSatis());
        plumUnsure.setSelected(feedBack.isPlumUnsure());
        plumNotSatis.setSelected(feedBack.isPlumNotSatis());
        
        sewVerySatis.setSelected(feedBack.isSewVerySatis());
        sewSatis.setSelected(feedBack.isSewSatis());
        sewUnsure.setSelected(feedBack.isSewUnsure());
        sewNotSatis.setSelected(feedBack.isSewNotSatis());
        
        otherComments.setText(feedBack.getComments());
        
        jSlider.setValue(feedBack.getRating());
        
        disableAllFeilds();
    }
}
