/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.EcoSystem;
import business.Tenant.Tenant;
import business.network.Network;
import business.account.Account;
import business.account.TenantAccount;
import business.enterprise.Enterprise;
import business.enterprise.GovernmentEnterprise;
import business.event.Event;
import business.organization.GovernmentAdminOrganization;
import business.organization.Organization;
import business.role.TenantRole;
import java.awt.CardLayout;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.Tenant.TenantWorkAreaJPanel;

/**
 *
 * @author Shruti
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;

    LoginJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        groupRadioButton();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        employeeRadioButton = new javax.swing.JRadioButton();
        userNameTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        SubmitBttn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        passwordFeild = new javax.swing.JPasswordField();
        tenantRadioButton = new javax.swing.JRadioButton();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/relocation.jpg"))); // NOI18N
        jLabel4.setMinimumSize(new java.awt.Dimension(341, 242));
        jLabel4.setPreferredSize(new java.awt.Dimension(341, 242));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Login Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        employeeRadioButton.setText("Employee");
        employeeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeRadioButtonActionPerformed(evt);
            }
        });

        userNameTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/username1.png"))); // NOI18N

        SubmitBttn.setBackground(new java.awt.Color(153, 51, 0));
        SubmitBttn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SubmitBttn.setForeground(new java.awt.Color(255, 255, 255));
        SubmitBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/icons8_Enter_20px_1.png"))); // NOI18N
        SubmitBttn.setText("Submit");
        SubmitBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBttnActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/index.jpg"))); // NOI18N

        passwordFeild.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tenantRadioButton.setText("Tenant");
        tenantRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SubmitBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tenantRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(employeeRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(userNameTxt)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(passwordFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(passwordFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeRadioButton)
                    .addComponent(tenantRadioButton))
                .addGap(31, 31, 31)
                .addComponent(SubmitBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(324, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBttnActionPerformed
        // TODO add your handling code here:
        String userName = userNameTxt.getText();
        String password = passwordFeild.getText();
        boolean isTenant = tenantRadioButton.isSelected();
        boolean isEmployee = employeeRadioButton.isSelected();
        

        Account userAccount = ecosystem.getAccountDirectory().authenticateUser(userName, password);
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        Network inNetwork = null;
        Event inEvent = null;
         if (isEmployee) {
            userAccount = ecosystem.getAccountDirectory().authenticateUser(userName, password);
            if (userAccount == null) {
                for (Network network : ecosystem.getNetworkList()) {
                    for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseDirectory()) {
                        userAccount = enterprise.getAccountDirectory().authenticateUser(userName, password);
                        if (userAccount == null) {
                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationDirectory()) {
                                userAccount = organization.getAccountDirectory().authenticateUser(userName, password);
                                if (userAccount != null) {
                                    inEnterprise = enterprise;
                                    inOrganization = organization;
                                    inNetwork = network;
                                    break;
                                }
                            }
                        } else {
                            inEnterprise = enterprise;
                            inNetwork = network;
                            break;
                        }
                        if (inOrganization != null) {
                            break;
                        }
                    }
                    if (inEnterprise != null) {
                        break;
                    }
                }
            }
        } else if (isTenant) {
            for (Network network : ecosystem.getNetworkList()) {
                GovernmentEnterprise governmentEnterprise = network.getEnterpriseDirectory().getGovernmentEnterprise();
                GovernmentAdminOrganization governmentAdminOrganization = governmentEnterprise.getOrganizationDirectory().getGovernmentAdminOrganization();
                for (Event event : governmentAdminOrganization.getEventList()) {
                    for (Account account : event.getAccountDirectory().getAccountDirectory()) {
                        if (account.getUsername().equals(userName) && account.getPassword().equals(password)) {
                            userAccount = account;
                            inEvent = event;
                        }
                    }
                }
            }
        }
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid Credentails!");
            return;
        } else if (isEmployee) {
            userProcessContainer.add("workArea", userAccount.getRole().createWorkArea(userProcessContainer, userAccount, inOrganization, inEnterprise, inNetwork, ecosystem));
            layout.next(userProcessContainer);
        } if (isTenant) {
            userProcessContainer.add("workArea", ((TenantRole) userAccount.getRole()).createWorkAreaJPanel(userProcessContainer, inEvent, userAccount, ecosystem));
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_SubmitBttnActionPerformed

    private void tenantRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantRadioButtonActionPerformed
        // TODO add your handling code here:
        tenantRadioButton.setSelected(true);
    }//GEN-LAST:event_tenantRadioButtonActionPerformed

    private void employeeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeRadioButtonActionPerformed
        // TODO add your handling code here:
        employeeRadioButton.setSelected(true);
    }//GEN-LAST:event_employeeRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitBttn;
    private javax.swing.JRadioButton employeeRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField passwordFeild;
    private javax.swing.JRadioButton tenantRadioButton;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables

    private void groupRadioButton() {
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(tenantRadioButton);
        bg1.add(employeeRadioButton);
    }
}
