/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.constructionAdminRole;

import business.account.Account;
import business.enterprise.ConstructionEnterprise;
import business.network.Network;
import business.organization.ConstructionAdminOrganization;
import business.project.Project;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hardik
 */
public class ConstructionAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConstructionAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Account account;
    private ConstructionAdminOrganization constructionAdminOrganization;
    private ConstructionEnterprise constructionEnterprise;
    private Network network;

    public ConstructionAdminWorkAreaJPanel() {
        initComponents();
    }

    public ConstructionAdminWorkAreaJPanel(JPanel userProcessContainer, Account account, ConstructionAdminOrganization constructionAdminOrganization, ConstructionEnterprise constructionEnterprise, Network network) {
        this();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.constructionAdminOrganization = constructionAdminOrganization;
        this.constructionEnterprise = constructionEnterprise;
        this.network = network;
        populateProjects();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        projectsTable = new javax.swing.JTable();
        initiateProjectButton = new javax.swing.JButton();
        manageProjectButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        projectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Budget", "Status", "Start Date"
            }
        ));
        jScrollPane1.setViewportView(projectsTable);

        initiateProjectButton.setBackground(new java.awt.Color(153, 51, 0));
        initiateProjectButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        initiateProjectButton.setForeground(new java.awt.Color(255, 255, 255));
        initiateProjectButton.setText("Initiate Project");
        initiateProjectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                initiateProjectButtonMouseClicked(evt);
            }
        });
        initiateProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initiateProjectButtonActionPerformed(evt);
            }
        });

        manageProjectButton.setBackground(new java.awt.Color(153, 51, 0));
        manageProjectButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        manageProjectButton.setForeground(new java.awt.Color(255, 255, 255));
        manageProjectButton.setText("Manage Project");
        manageProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProjectButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Initiate Project");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(initiateProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(106, 106, 106)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(initiateProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(239, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initiateProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initiateProjectButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_initiateProjectButtonActionPerformed

    private void initiateProjectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_initiateProjectButtonMouseClicked
        // TODO add your handling code here:
        CreateProjectJPanel cpjp = new CreateProjectJPanel(userProcessContainer, account, constructionAdminOrganization, constructionEnterprise, network);
        userProcessContainer.add(cpjp);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_initiateProjectButtonMouseClicked

    private void manageProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProjectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageProjectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton initiateProjectButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageProjectButton;
    private javax.swing.JTable projectsTable;
    // End of variables declaration//GEN-END:variables

    public void populateProjects() {
        DefaultTableModel dtm = (DefaultTableModel) projectsTable.getModel();
        dtm.setRowCount(0);
        for (Project project : constructionAdminOrganization.getProjects()) {
            Object[] row = new Object[4];
            row[0] = project;
            row[1] = project.getBudget();
            row[2] = project.getProjectStatus();
            row[3] = project.getStartDate();
            dtm.addRow(row);
        }
    }
}
