/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Admin;

import business.account.Account;
import business.enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Shruti
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Account account;
    
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Account account) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.enterprise = enterprise;
       this.account = account;
       adminNameLbl.setText(account.getEmployee().getFirstName().concat(" ").concat(account.getEmployee().getLastName()));
       valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminNameLbl = new javax.swing.JLabel();
        manageEmployeeBttn = new javax.swing.JButton();
        manageAccountsBttn = new javax.swing.JButton();
        mngeOrganizationBttn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Aminstrative Role");

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setText("<value>");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Welcome ");

        adminNameLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adminNameLbl.setText("jLabel2");

        manageEmployeeBttn.setBackground(new java.awt.Color(153, 51, 0));
        manageEmployeeBttn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        manageEmployeeBttn.setForeground(new java.awt.Color(255, 255, 255));
        manageEmployeeBttn.setText("Manage Employee");
        manageEmployeeBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageEmployeeBttnMouseClicked(evt);
            }
        });
        manageEmployeeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeBttnActionPerformed(evt);
            }
        });

        manageAccountsBttn.setBackground(new java.awt.Color(153, 51, 0));
        manageAccountsBttn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        manageAccountsBttn.setForeground(new java.awt.Color(255, 255, 255));
        manageAccountsBttn.setText("Manage Accounts");
        manageAccountsBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageAccountsBttnMouseClicked(evt);
            }
        });
        manageAccountsBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccountsBttnActionPerformed(evt);
            }
        });

        mngeOrganizationBttn.setBackground(new java.awt.Color(153, 51, 0));
        mngeOrganizationBttn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mngeOrganizationBttn.setForeground(new java.awt.Color(255, 255, 255));
        mngeOrganizationBttn.setText("Manage Organization");
        mngeOrganizationBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mngeOrganizationBttnMouseClicked(evt);
            }
        });
        mngeOrganizationBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngeOrganizationBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adminNameLbl))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(manageAccountsBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageEmployeeBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mngeOrganizationBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(adminNameLbl))
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(valueLabel)))
                .addGap(36, 36, 36)
                .addComponent(mngeOrganizationBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageEmployeeBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageAccountsBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageEmployeeBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEmployeeBttnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_manageEmployeeBttnMouseClicked

    private void manageEmployeeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeBttnActionPerformed
        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEmployeeBttnActionPerformed

    private void manageAccountsBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAccountsBttnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_manageAccountsBttnMouseClicked

    private void manageAccountsBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccountsBttnActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAccountsBttnActionPerformed

    private void mngeOrganizationBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mngeOrganizationBttnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mngeOrganizationBttnMouseClicked

    private void mngeOrganizationBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngeOrganizationBttnActionPerformed
        // TODO add your handling code here:
        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngeOrganizationBttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminNameLbl;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageAccountsBttn;
    private javax.swing.JButton manageEmployeeBttn;
    private javax.swing.JButton mngeOrganizationBttn;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
