/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SystemAdminWorkArea;

import business.EcoSystem;
import business.account.Account;
import business.employee.Employee;
import business.enterprise.Enterprise;
import business.network.Network;
import business.role.AdminRole;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shruti
 */


public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseAdminJTable = new javax.swing.JTable();
        viewBttn = new javax.swing.JButton();
        backBttn = new javax.swing.JButton();
        deleteBttn = new javax.swing.JButton();
        addAdmin = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Enterprise Admin");

        enterpriseAdminJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Enterprise Name", "Network"
            }
        ));
        jScrollPane1.setViewportView(enterpriseAdminJTable);

        viewBttn.setBackground(new java.awt.Color(153, 51, 0));
        viewBttn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        viewBttn.setForeground(new java.awt.Color(255, 255, 255));
        viewBttn.setText("View Admin");
        viewBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewBttnMouseClicked(evt);
            }
        });
        viewBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBttnActionPerformed(evt);
            }
        });

        backBttn.setBackground(new java.awt.Color(153, 51, 0));
        backBttn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        backBttn.setForeground(new java.awt.Color(255, 255, 255));
        backBttn.setText("<<Back");
        backBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBttnMouseClicked(evt);
            }
        });
        backBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttnActionPerformed(evt);
            }
        });

        deleteBttn.setBackground(new java.awt.Color(153, 51, 0));
        deleteBttn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deleteBttn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBttn.setText("Delete Button");
        deleteBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBttnMouseClicked(evt);
            }
        });
        deleteBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBttnActionPerformed(evt);
            }
        });

        addAdmin.setBackground(new java.awt.Color(153, 51, 0));
        addAdmin.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addAdmin.setForeground(new java.awt.Color(255, 255, 255));
        addAdmin.setText("Add Admin >>");
        addAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAdminMouseClicked(evt);
            }
        });
        addAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(backBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(deleteBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(404, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(deleteBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(backBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBttnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewBttnMouseClicked

    private void viewBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBttnActionPerformed
        // TODO add your handling code here:
        int selectedRow = enterpriseAdminJTable.getSelectedRow();
        int pic = JOptionPane.ERROR_MESSAGE;
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a record to view", "", pic);
        } else {
            Enterprise enterprise = (Enterprise) enterpriseAdminJTable.getValueAt(selectedRow, 1);
            Network network = (Network) enterpriseAdminJTable.getValueAt(selectedRow, 2);
            Account userAccount = (Account) enterpriseAdminJTable.getValueAt(selectedRow, 0);
            
            ViewAdminJPanel viewEnterpriseAdminJPanel = new ViewAdminJPanel(userProcessContainer, network,enterprise,userAccount);
            userProcessContainer.add("ViewEnterpriseAdminJPanel", viewEnterpriseAdminJPanel);
            CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        }
    }//GEN-LAST:event_viewBttnActionPerformed

    private void backBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBttnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backBttnMouseClicked

    private void backBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttnActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBttnActionPerformed

    private void deleteBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBttnMouseClicked
        
    }//GEN-LAST:event_deleteBttnMouseClicked

    private void deleteBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBttnActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int selectedRow = enterpriseAdminJTable.getSelectedRow();
        int pic = JOptionPane.ERROR_MESSAGE;
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select an Admin to delete", "", pic);
        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete Admin", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Enterprise enterprise = (Enterprise) enterpriseAdminJTable.getValueAt(selectedRow, 1);
                Network network = (Network) enterpriseAdminJTable.getValueAt(selectedRow, 2);
                Account userAccount = (Account) enterpriseAdminJTable.getValueAt(selectedRow, 0);
                for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseDirectory()) {
                    if (e.getName().equalsIgnoreCase(enterprise.getName())) {
                        enterprise.getAccountDirectory().removeAccount(userAccount);
                        JOptionPane.showMessageDialog(null, "Account Deleted Successfully");
                        populateTable();
                    }
                }
            }
        }
    }//GEN-LAST:event_deleteBttnActionPerformed

    private void addAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAdminMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addAdminMouseClicked

    private void addAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminActionPerformed
        // TODO add your handling code here:
        AddAdminWorkAreaJPanel addAdminWorkAreaJPanel = new AddAdminWorkAreaJPanel(userProcessContainer,ecoSystem);
        userProcessContainer.add("addAdminWorkAreaJPanel",addAdminWorkAreaJPanel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
        
    }//GEN-LAST:event_addAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdmin;
    private javax.swing.JButton backBttn;
    private javax.swing.JButton deleteBttn;
    private javax.swing.JTable enterpriseAdminJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewBttn;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseAdminJTable.getModel();

        model.setRowCount(0);
        for (Network network : ecoSystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseDirectory()) {
                for (Account userAccount : enterprise.getAccountDirectory().getAccountDirectory()) {
                    Object[] row = new Object[3];
                    row[0] = userAccount;
                    row[1] = enterprise;                   
                    row[2] = network;
                    model.addRow(row);
                }
            }
        }
    }
}
